[skelly.package]
name = "skelly"
version = "0.0.0"

[skelly.toolchain]
ghc = ">= 9.10 && < 9.12"

[skelly.dependencies]
aeson = "^2.2.3.0"
base = "^4.20.0.0"
base16-bytestring = "^1.0.2.0"
bytestring = "^0.12.1.0"
Cabal-syntax = "^3.14.1.0"
cabal-install = "^3.14.1.0"
containers = "^0.7"
crypton = "^1.0.4"
data-interval = "^2.1.2"
directory = "^1.3.8.3"
file-embed = "^0.0.16.0"
filepath = "^1.5.2.0"
HList = "^0.5.4.0"
hackage-security = "^0.6.2.6"
http-client = "^0.7.18"
http-client-tls = "^0.3.6.4"
http-types = "^0.12.4"
lrucache = "^1.2.0.1"
megaparsec = "^9.7.0"
monad-validate = "^1.3.0.0"
network-uri = "^2.6.4.2"
optparse-applicative = "^0.18.1.0"
process = "^1.6.19.0"
psqueues = "^0.2.8.0"
serialise = "^0.2.6.1"
tar = "^0.6.4.0"
text = "^2.1.2"
time = "^1.12.2"
toml-reader = "^0.2.1.0"
transformers = "^0.6.1.1"
unliftio = "^0.2.25.0"
zlib = "^0.7.1.0"
