[skelly.package]
name = "skelly"
version = "0.0.0"

[skelly.toolchain]
ghc = ">= 9.10 && < 9.12"

[skelly.dependencies]
aeson = "< 3"
base = "< 5"
bytestring = "< 1"
Cabal-syntax = "< 4"
cabal-install = "< 4"
containers = "< 1"
data-interval = "< 3"
directory = "< 2"
file-embed = ">= 0.0.9 && < 1"
filepath = "< 2"
hackage-security = "< 1"
http-client = "< 1"
http-client-tls = "< 1"
http-types = "< 1"
megaparsec = "< 10"
network-uri = "< 3"
optparse-applicative = "< 1"
process = "< 2"
serialise = "< 1"
text = "< 3"
time = "< 2"
toml-reader = "< 1"
transformers = "< 1"
unliftio = "< 1"
